name: "API test"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
              with:
                submodules: recursive
            - name: setup-env
              run: sudo apt install cmake sqlite3 gcc curl jq
            - name: build
              run: cmake -B build && cmake --build build
              env:
                CXX: g++-13
            - name: run-test
              run: ./build/src/backend --port $(cat ./files/testdata/default.json | jq -r .port) & sleep 1 && bash ./tests/api-test.sh 