name: "Backend tests"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
              with:
                submodules: recursive
            - name: setup-env
              run: sudo apt install cmake sqlite3 libasio-dev gcc
            - name: build
              run: cmake -B build && cmake --build build
              env:
                CXX: g++-13
            - name: test-all
              run: ctest --test-dir build