name: "Backend tests"

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test-all:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
                cache: 'pip'
            - run: pip install -r requirements.txt
            - name: test-all
              run: pytest tests